"""Add plain_password to User model

Revision ID: 27d1ce63ed93
Revises: 20e1cb61c152
Create Date: 2025-02-09 22:19:29.759351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27d1ce63ed93'
down_revision: Union[str, None] = '20e1cb61c152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
