name: Multi-Environment Deployment

on:
  push:
    branches:
      - main     # Deploy to production
      - develop  # Deploy to staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Determine Environment
      id: set-env
      run: |
        if [ "${{ github.ref_name }}" == "main" ]; then
          echo "env=production" >> $GITHUB_ENV
        else
          echo "env=staging" >> $GITHUB_ENV
          
    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        APP_ENV: ${{ env.env }}
      run: |
        echo "Deploying to $APP_ENV environment..."
        curl -X POST \
        -H "Accept: application/json" \
        -H "Authorization: Bearer $RENDER_API_KEY" \
        -H "Content-Type: application/json" \
        -d '{"clearCache":false}' \
        https://api.render.com/v1/services/your-render-service-id/deploys
