name: Deploy to Render

on:
  push:
    branches:
      - main  # Triggers deployment on every push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest  # Ensure all tests pass before deploying

    - name: Notify Render to Deploy
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      run: |
        echo "Deploying to Render..."
        curl -X POST \
        -H "Accept: application/json" \
        -H "Authorization: Bearer $RENDER_API_KEY" \
        -H "Content-Type: application/json" \
        -d '{"clearCache":false}' \
        https://api.render.com/v1/services/your-render-service-id/deploys
